// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd2FzW2eVRrHz4LW-TAua-L4BOZtN4VQw',
    appId: '1:72605764706:web:80621e872ad578efbc953b',
    messagingSenderId: '72605764706',
    projectId: 'bloogol-e8399',
    authDomain: 'bloogol-e8399.firebaseapp.com',
    storageBucket: 'bloogol-e8399.firebasestorage.app',
    measurementId: 'G-4XNVG83R84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb1zII6rnCwMxdlFRSRZcpeZjPE5kgC4w',
    appId: '1:72605764706:android:a6d4be4cf1306886bc953b',
    messagingSenderId: '72605764706',
    projectId: 'bloogol-e8399',
    storageBucket: 'bloogol-e8399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSH34xT6rH53Kcezvmfb5RjyObBD8Epo',
    appId: '1:72605764706:ios:c86c88f4e5f19045bc953b',
    messagingSenderId: '72605764706',
    projectId: 'bloogol-e8399',
    storageBucket: 'bloogol-e8399.firebasestorage.app',
    iosBundleId: 'com.example.newApplicationApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSH34xT6rH53Kcezvmfb5RjyObBD8Epo',
    appId: '1:72605764706:ios:c86c88f4e5f19045bc953b',
    messagingSenderId: '72605764706',
    projectId: 'bloogol-e8399',
    storageBucket: 'bloogol-e8399.firebasestorage.app',
    iosBundleId: 'com.example.newApplicationApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd2FzW2eVRrHz4LW-TAua-L4BOZtN4VQw',
    appId: '1:72605764706:web:d5ceb74805bc5281bc953b',
    messagingSenderId: '72605764706',
    projectId: 'bloogol-e8399',
    authDomain: 'bloogol-e8399.firebaseapp.com',
    storageBucket: 'bloogol-e8399.firebasestorage.app',
    measurementId: 'G-73K1MSVVKN',
  );
}
